# Setup script for Windows
# Run this script on your Windows PC to configure the project

Write-Host "==========================================" -ForegroundColor Cyan
Write-Host "Body Scan App - Windows Setup" -ForegroundColor Cyan
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host ""

$ProjectRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $ProjectRoot

# Step 1: Check Java 21
Write-Host "1. Checking Java 21 installation..." -ForegroundColor Yellow
$Java21Path = ""

# Check in .java directory (project-local)
$JavaLocalPath = Join-Path $ProjectRoot ".java\jdk-21.0.9+10"
if (Test-Path $JavaLocalPath) {
    $Java21Path = $JavaLocalPath
    Write-Host "   ✓ Found Java 21 in .java directory" -ForegroundColor Green
}
# Check common Windows installation locations
elseif (Test-Path "C:\Program Files\Java\jdk-21") {
    $Java21Path = "C:\Program Files\Java\jdk-21"
    Write-Host "   ✓ Found Java 21 in Program Files" -ForegroundColor Green
}
elseif (Test-Path "$env:JAVA_HOME") {
    $JavaVersion = & java -version 2>&1 | Select-String "21"
    if ($JavaVersion) {
        $Java21Path = $env:JAVA_HOME
        Write-Host "   ✓ Found Java 21 in JAVA_HOME" -ForegroundColor Green
    }
}
else {
    Write-Host "   ⚠ Java 21 not found. Please install Java 21:" -ForegroundColor Yellow
    Write-Host "   Download from: https://adoptium.net/temurin/releases/?version=21" -ForegroundColor Yellow
    Write-Host "   Or install via Chocolatey: choco install temurin21" -ForegroundColor Yellow
    Write-Host ""
    $Java21Path = Read-Host "Enter Java 21 installation path (or press Enter to skip)"
}

# Step 2: Create gradle.properties.local
Write-Host ""
Write-Host "2. Creating gradle.properties.local..." -ForegroundColor Yellow

if ($Java21Path) {
    # Convert to Windows path format for Gradle
    $Java21Path = $Java21Path -replace '\\', '\\'
    
    $GradleProps = @"
# Windows-specific Gradle properties
# Auto-generated by setup_windows.ps1 - DO NOT EDIT MANUALLY

# JVM arguments
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 --enable-native-access=ALL-UNNAMED

# Java 21 home (Windows-specific path)
org.gradle.java.home=$Java21Path

# AndroidX
android.useAndroidX=true

# Kotlin
kotlin.code.style=official

# R class namespacing
android.nonTransitiveRClass=true
"@
} else {
    $GradleProps = @"
# Windows-specific Gradle properties
# Auto-generated by setup_windows.ps1 - DO NOT EDIT MANUALLY
# NOTE: Java 21 path not configured. Please add it manually:
# org.gradle.java.home=C:\\Path\\To\\Java\\jdk-21

# JVM arguments
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 --enable-native-access=ALL-UNNAMED

# AndroidX
android.useAndroidX=true

# Kotlin
kotlin.code.style=official

# R class namespacing
android.nonTransitiveRClass=true
"@
}

$GradleProps | Out-File -FilePath "gradle.properties.local" -Encoding UTF8
Write-Host "   ✓ Created gradle.properties.local" -ForegroundColor Green

# Step 3: Check OpenCV
Write-Host ""
Write-Host "3. Checking OpenCV setup..." -ForegroundColor Yellow
$OpenCVConfig = Join-Path $ProjectRoot "opencv-android-sdk\sdk\native\jni\OpenCVConfig.cmake"
if (Test-Path $OpenCVConfig) {
    Write-Host "   ✓ OpenCV is already set up" -ForegroundColor Green
} else {
    Write-Host "   ⚠ OpenCV not set up. Run .\setup_opencv.ps1 to download it." -ForegroundColor Yellow
}

# Step 4: Check local.properties
Write-Host ""
Write-Host "4. Checking local.properties..." -ForegroundColor Yellow
if (-not (Test-Path "local.properties")) {
    Write-Host "   ⚠ local.properties not found. Android Studio will create it automatically." -ForegroundColor Yellow
    Write-Host "   Or create it manually with:" -ForegroundColor Yellow
    Write-Host "   sdk.dir=C:\\Users\\$env:USERNAME\\AppData\\Local\\Android\\Sdk" -ForegroundColor Yellow
} else {
    Write-Host "   ✓ local.properties exists" -ForegroundColor Green
}

Write-Host ""
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host "Windows Setup Complete!" -ForegroundColor Cyan
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "  1. If OpenCV is not set up: .\setup_opencv.ps1" -ForegroundColor White
Write-Host "  2. Open project in Android Studio" -ForegroundColor White
Write-Host "  3. Sync Gradle files" -ForegroundColor White
Write-Host "  4. Build: .\gradlew.bat assembleDebug" -ForegroundColor White
Write-Host ""

