#!/bin/bash
# Setup script for macOS
# Run this script on your Mac to configure the project

set -e

echo "=========================================="
echo "Body Scan App - macOS Setup"
echo "=========================================="
echo ""

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$PROJECT_ROOT"

# Step 1: Check Java 21
echo "1. Checking Java 21 installation..."
JAVA_21_PATH=""

# Check in .java directory (project-local)
if [ -d ".java/jdk-21.0.9+10/Contents/Home" ]; then
    JAVA_21_PATH="${PROJECT_ROOT}/.java/jdk-21.0.9+10/Contents/Home"
    echo "   ✓ Found Java 21 in .java directory"
elif [ -d "/opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home" ]; then
    JAVA_21_PATH="/opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home"
    echo "   ✓ Found Java 21 via Homebrew"
elif [ -d "/Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home" ]; then
    JAVA_21_PATH="/Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home"
    echo "   ✓ Found Java 21 system installation"
else
    echo "   ⚠ Java 21 not found. Will download to .java directory..."
    echo "   Downloading Java 21..."
    mkdir -p .java
    cd .java
    curl -L -o jdk21.tar.gz "https://api.adoptium.net/v3/binary/latest/21/ga/mac/aarch64/jdk/hotspot/normal/eclipse" 2>&1 | tail -1
    tar -xzf jdk21.tar.gz
    JAVA_DIR=$(ls -d jdk-21* | head -1)
    JAVA_21_PATH="${PROJECT_ROOT}/.java/${JAVA_DIR}/Contents/Home"
    rm -f jdk21.tar.gz
    cd "$PROJECT_ROOT"
    echo "   ✓ Java 21 downloaded to .java directory"
fi

# Step 2: Create gradle.properties.local
echo ""
echo "2. Creating gradle.properties.local..."
cat > gradle.properties.local << EOF
# macOS-specific Gradle properties
# Auto-generated by setup_mac.sh - DO NOT EDIT MANUALLY

# JVM arguments
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 --enable-native-access=ALL-UNNAMED

# Java 21 home (Mac-specific path)
org.gradle.java.home=${JAVA_21_PATH}

# AndroidX
android.useAndroidX=true

# Kotlin
kotlin.code.style=official

# R class namespacing
android.nonTransitiveRClass=true
EOF

echo "   ✓ Created gradle.properties.local with Java path: $JAVA_21_PATH"

# Step 3: Check OpenCV
echo ""
echo "3. Checking OpenCV setup..."
if [ -f "opencv-android-sdk/sdk/native/jni/OpenCVConfig.cmake" ]; then
    echo "   ✓ OpenCV is already set up"
else
    echo "   ⚠ OpenCV not set up. Run ./setup_opencv.sh to download it."
fi

# Step 4: Check local.properties
echo ""
echo "4. Checking local.properties..."
if [ ! -f "local.properties" ]; then
    echo "   ⚠ local.properties not found. Android Studio will create it automatically."
    echo "   Or create it manually with:"
    echo "   sdk.dir=/Users/$(whoami)/Library/Android/sdk"
else
    echo "   ✓ local.properties exists"
fi

echo ""
echo "=========================================="
echo "macOS Setup Complete!"
echo "=========================================="
echo ""
echo "Next steps:"
echo "  1. If OpenCV is not set up: ./setup_opencv.sh"
echo "  2. Open project in Android Studio"
echo "  3. Sync Gradle files"
echo "  4. Build: ./gradlew assembleDebug"
echo ""
echo "Note: gradle.properties.local ensures Java 21 is used automatically"
echo ""

